### ISSUE TITLE
building for switch

### ISSUE THREAD

**Issue by MEPO29** [krkrsdl2/krkrsdl2#102]
Hello. I am trying to build for switch on windows using devkitPro, have failed after many tries on ARM64 OSX, now moved to a windows machine. 

When trying to build with CMake I get the following error:
```
CMake Error in CMakeLists.txt:
  Found relative path while evaluating include directories of "krkrsdl2":

    "C:/Users/mepop/krkrsdl2/src/core/base/sdl2"
```
Any help would be greatly appreciated.

**Comment by uyjulian** [comment]
The instructions for building for switch is here: https://github.com/krkrsdl2/krkrsdl2/blob/cfebfaa4686a0d9169eb4fa9760d37711231694b/.github/workflows/ci.yml#L309

Be aware that it is not actively tested so behavior may be broken
