### ISSUE TITLE
win32 plugin on other platforms

### ISSUE THREAD

**Issue by PYUDNG** [krkrsdl2/krkrsdl2#114]
Platform: MacOS
Game: ATRI -My Dear Moments- (Chinese ver.) (Tested in Kirikiroid on Android which worked fine)

This is about loading some win32 plugins on MacOS.
I've already read #2 and #53. From these issues, I learned that krkrsdl2 supports .dll plugins on windows, and Wine+windows version can be used on MacOS. But when I actually tried _Wine + krkrsdl2 windows version_ on my mac, there's errors thrown out.
<details><summary>Here's some err output (if you're interested)</summary>
When I start the game with wine and tvpwin64.exe, a alertbox saying <code>Script exception raised. script exception : Cannot load Plugin win32dialog.dll</code> popped out and the game launching failed.

After some googling I found [this issue](https://github.com/krkrz/Krkr2Compat/issues/3) in [krkrz/Krkr2Compat/](https://github.com/krkrz/Krkr2Compat), which told me that win32dialog.dll is 32-bit and should be loaded with 32-bit programs. So I tried this: <code>wine64 tvpwin32.exe ...path to the game directory\data.xp3</code>, but found another error come out: <code>wine: Unhandled page fault on execute access to 0012F51C at address 0012F51C (thread 0104), starting debugger...</code>
</details>
I don't know whether it is a wine or krkrsdl2 bug, or just 64-bit macos cannot load game with 32-bit windows plugins.
Is there any way to run the game with krkrsdl2 on MacOS (with or without Wine)?
<br><br>

Besides, in #2:
> Looks like Emscripten supports dynamic linking… https://github.com/emscripten-core/emscripten/wiki/Linking

Does that mean win32 plugins are supported in web version? I've tried both _macos version_, _windows version(with Wine)_ and _web version_ but none of these launched the game successfully. The web version says `Cannot load Plugin win32dialog.dll` as well.

**Comment by uyjulian** [comment]
A few things:
1. ***unmodified*** **commercial** games are not supported, and I don't plan to work on that due to the large amount of work needed (Due to this fact, this issue will be closed). If it doesn't work on unmodified/upstream Kirikiri Z, it will not work on Kirikiri SDL2.  
2. Win32 plugins only work on Win32.  
3. There is an issue with exception handling in Win32 for Intel 32-bit architecture.
