### ISSUE TITLE
tTVPBitmapBitsAlloc::Free issue

### ISSUE THREAD

**Issue by uyjulian** [krkrsdl2/krkrsdl2#40]
`tTVPBitmapBitsAlloc::Free` is being called in destructor of class `tTVPBitmap`.
`tTVPBitmapBitsAlloc::Free` can throw an exception when sentinel is corrupted (e.g. buffer overrun). However, exception cannot be handled gracefully in program exit

**Comment by xyx0no646** [comment]
Thank you for creating this issue!

This issue reproduces on iOS Krkr sdl2 and generates a crash log to TestFlight.
However,When commented out, it seems to exit without crash log on the surface.

Do you think there are any problem(s) with commenting out the relevant line in the tTVPBitmap destructor?

**Comment by uyjulian** [comment]
The problem with commenting out the line is that it creates a memory leak.

In 75decf28135595cfeaa46c53fb7e79e582f6f884, I changed the exception to a log, so it shouldn't cause any issues anymore.

**Comment by uyjulian** [comment]
This specific instance of the issue is caused by the vector tvpgl code having overrun, but this can be worked around by disabling it via command line arguments `-cpummx=no` `-cpusse=no` `-cpusse2=no` etc.

The underlying issue of throwing exception in destructor has been changed, so this issue has been fixed.
