### ISSUE TITLE
[Suggestion] Win32 builds.

### ISSUE THREAD

**Issue by lochana-Dineko** [krkrsdl2/krkrsdl2#55]
This isn't really an issue but I wonder if you could (if at all possible) also provide Windows Builds alongside Mac and Linux Binaries. Kirkiri Z works fine on windows but I would like to test and work with Krkrsdl2 too. I'm working on my own project with Kirkiri Z and it would be nice if it works with this out of the box. Future Kag developers will probably utilize this.

Thanks in Advance.

**Comment by uyjulian** [comment]
There is really no point in Windows builds of Kirikiri SDL2 since Kirikiri Z works fine and I contribute the changes upstream.

**Comment by lochana-Dineko** [comment]
Alright then. Thanks for your time. I'll close this issue.
