### ISSUE TITLE
How to play video?

### ISSUE THREAD

**Issue by Yamilemon** [krkrsdl2/krkrsdl2#85]
I use kag [Video] to play a video, but it doesn't  work.

Although I can use the video element in HTML to play the video, I want to know if the krkrsdl2 has a way to play the video?

If krkr2sdl can play video, what TJS code should I write to play the video?

**Comment by uyjulian** [comment]
You can use the video element in HTML.

TJS video playback is currently not implemented. See #52

**Comment by Yamilemon** [comment]
OK.
