### ISSUE TITLE
psbfile plugin?

### ISSUE THREAD

**Issue by marcussacana** [krkrsdl2/krkrsdl2#86]
I think this project is very interesing, do you have any plans to make a PSB/SCN implementation?
that can made the krkrsdl2 more near to run modern games, or at least more easy to modify that games to works.

**Comment by uyjulian** [comment]
Once I finish the Win32 and external plugin support, you will be able to load the psbfile.dll plugin.  

For other platforms, I'll only port plugins that have source code available.

**Comment by marcussacana** [comment]
I see, the krkrdroid work with games that use PSB, but no idea if that part is open source.
