### ISSUE TITLE
Run the uncompressed game data file on the browser

### ISSUE THREAD

**Issue by Pevernow** [krkrsdl2/krkrsdl2#91]
Run the uncompressed game data file on the browser instead of loading an entire XP3 into the browser.

A large-scale game data file can reach more than 1GB.

It takes a long time to load all of them from the web server and it may cause lagging.

Moreover, compared with the decompressed multimedia files, the huge data files are not conducive to CDN transmission

Can you add support for running TJS scripts in the browser instead of loading the entire XP3?

**Comment by uyjulian** [comment]
Running of individual TJS scripts can be done by `Module.evalTJS` in a JS script.  
For downloading individual files, can use Fetch or XMLHttpRequest.  

See the following for more detailed documentation of the browser interface.  
https://github.com/krkrsdl2/krkrsdl2/wiki/Web%E7%89%88%E5%90%89%E9%87%8C%E5%90%89%E9%87%8CSDL2-JS%E2%87%94TJS-%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%95%E3%82%A7%E3%83%BC%E3%82%B9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
