### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by uyjulian** [krkrsdl2/krkrsdl2#96]
This is a meta-issue for breaking changes before 1.0.0 release.

1. `-s MODULARIZE=1` will be enabled. This will change how it is initialized in the html. **Fully implemented**  
2. External plugins will be implemented by default, so `Plugins.link` will no longer be a no-op. **Fully implemented**  
3. As a result of 2, certain plugins will no longer be integrated. **Fully implemented**
4. Change to use the CMake build system, and remove usage of Meson entirely. **Fully implemented**

**Comment by aq1018** [comment]
Does this mean plugins will work in webasm builds on main branch?

**Comment by uyjulian** [comment]
> Does this mean plugins already work in webasm builds on main branch?

Once the external plugins by default change is implemented, they will work.

**Comment by uyjulian** [comment]
All breaking changes have been fully implemented.
